#!/bin/bash

docker run --rm -i \
  -v /var/log/ansible/ansible.log \
  -v /var/lib/jenkins/.ssh:/home/jenkins/.ssh \
  -v "$(pwd)"/naisible:/ansible/playbooks \
  -v "$(pwd)"/nais-inventory:/ansible/inventory \
  -e F5_USER \
  -e F5_PASSWORD \
  navikt/ansible-playbook:2.4.6.0 "$@"
