- hosts: localhost
  tasks:
  - name: Ensure kube directory exists
    file:
      state: directory
      path: "{{ cluster_name }}"

- hosts: masters
  user: deployer
  become: yes
  tasks:
  - name: Ensure clean directory
    file:
      path: "{{ cluster_name }}/config"
      state: absent
  - name: Fetch cluster-admin from master
    fetch:
      src: /etc/kubernetes/kubeconfigs/cluster-admin.conf
      dest: "{{ cluster_name }}/config"
      flat: yes
