---
- hosts: localhost
  tasks:
  - name: Ensure kube directory exists
    file: state=directory path={{cluster_name}}

- hosts: masters
  user: deployer
  become: yes
  tasks:

  - name: fetch nais-admin from master
    fetch: src=/etc/kubernetes/kubeconfigs/nais-admin.conf dest={{cluster_name}}/config flat=yes
